# All the default ArchWRLD aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/archwrld/default/zsh/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
